# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('raw_query', models.TextField()),
                ('raw_request_headers', models.TextField()),
                ('raw_request_body', models.TextField()),
                ('http_code', models.IntegerField()),
                ('http_reason', models.CharField(max_length=100)),
                ('raw_response_headers', models.TextField()),
                ('raw_response_body', models.TextField()),
                ('app_name', models.CharField(default='', max_length=100)),
                ('url_name', models.CharField(default='', max_length=100)),
                ('view_name', models.CharField(default='', max_length=100)),
                ('func_name', models.CharField(default='', max_length=100)),
                ('exception', models.CharField(max_length=100)),
                ('traceback', models.TextField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField()),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
