# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='exception',
            field=models.TextField(max_length=100),
        ),
    ]
