# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_log', '0002_auto_20170503_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='django_error_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
